# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/EntrustedAI',
                'doc_host': 'https://entrustedai.github.io',
                'git_url': 'https://github.com/entrustedai/EntrustedAI',
                'lib_path': 'EntrustedAI'},
  'syms': {'EntrustedAI.core': {'EntrustedAI.core.foo': ('core.html#foo', 'EntrustedAI/core.py')}}}
